service: wss-sinais

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  pythonRequirements:
    usePoetry: false
    fileName: requirements.txt
    zip: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:ssm:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":parameter/telegram-token"
        - Fn::Join:
            - ""
            - - "arn:aws:ssm:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":parameter/senha-modal-mt5"
functions:
  bot:
    handler: saida/bot.lambda_handler
    events:
      - http: POST /
plugins:
  - serverless-python-requirements
